FROM python:3.9

WORKDIR /code

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["C:\\Users\\professor\\Desktop\\joao pedro capel\\FACULDADE\\PROVAS GELZIENE\\provaSITEGABRIEL\\prova\\virtual\\Scripts\\python.exe", "manage.py", "runserver", "0.0.0.0:8000"]

